### ISSUE TITLE
no left hand pcb files 

### ISSUE THREAD

**Issue by bubismark** [Ergodox-io/ErgoDox#13]
maybe im missing something (maybe its the same design for both hands) i have read thru https://www.ergodox.io/ and looked around and cant seem to find the schematics  for the left hand , 
in all the files (i opened them using kicad) i only see board design files(.kicad_pcb) for right hand. 
what am i missing ?

**Comment by jp94260** [comment]
The left and right pcb are the same just flipped, so it is maybe on the same file juste have to flip or equivalent ? 
I not have any certitude of anything I just deducing from watching my pcb freshly received.

**Comment by bubismark** [comment]
wow 10x man you are correct once i looked in  3d mode and could rotate i saw its the left side.
thank you
