### ISSUE TITLE
Right hand size 10 times bigger

### ISSUE THREAD

**Issue by Tom-Pietri** [Ergodox-io/ErgoDox#6]
The right hand appears to be 10 times biger than the left one (side going for 2000mm...)

Is it normal?

**Comment by robotmaxtron** [comment]
No, I can't imagine it is. Do you mean the pcb or one of the case files? @Tom-Pietri

**Comment by greizgh** [comment]
This concerns the case files. The scale for right hand dxf files (both standard case and wrist rest case) is off.

**Comment by robotmaxtron** [comment]
@greizgh Thanks, I'll take a look and see if I can't take a look at fixing it.

**Comment by Vvalter** [comment]
This does not seem to be fixed. The right hand size is still much bigger.

**Comment by robotmaxtron** [comment]
@Vvalter This should be fixed now, can you confirm?

**Comment by Vvalter** [comment]
Yes this is fixed now. Thanks @robotmaxtron and @greizgh !
